server:
  port: 8080
  autostart: false
webcams:
  - shortName: "cam0"
    webcamName: "EpocCam Camera"
    identifier: "\\\\?\\root#media#0001#{e5323777-f976-4f5b-9b55-b94699c46e44}\\{45ab5b3b-2e15-4452-a2cb-87e5fdd026fb}"
    used: false
  - shortName: "cam1"
    webcamName: "XSplit VCam"
    identifier: "\\\\?\\root#image#0000#{e5323777-f976-4f5b-9b55-b94699c46e44}\\global"
    used: true
